package tspsolver.model.updates;

public enum UpdateAction {

	ADD_NODE, REMOVE_NODE,
	ADD_STARTING_NODE, REMOVE_STARTING_NODE,
	ADD_EDGE, REMOVE_EDGE,
	PATH_ELEMENT, NON_PATH_ELEMENT, NEW_PATH_ELEMENT, OLD_PATH_ELEMENT;

}
