package streuli;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;

import javax.swing.JPanel;

import com.kitfox.svg.SVGCache;
import com.kitfox.svg.app.beans.SVGIcon;

class IconPanel2 extends JPanel {
	public static final long serialVersionUID = 0;

	final SVGIcon test;

	public IconPanel2() throws IOException {

		InputStream svgImage = this.getClass().getClassLoader().getResourceAsStream("map/switzerland.svg");
		URI uri = SVGCache.getSVGUniverse().loadSVG(svgImage, "map_switzerland");

		test = new SVGIcon();
		test.setSvgURI(uri);

		setPreferredSize(new Dimension(400, 400));
	}

	@Override
	public void paintComponent(Graphics g) {
		final int width = getWidth();
		final int height = getHeight();

		g.setColor(getBackground());
		g.fillRect(0, 0, width, height);

		test.setPreferredSize(new Dimension(400, 256));
		test.setScaleToFit(true);
		test.paintIcon(this, g, 0, 0);
	}
}

public class Test extends javax.swing.JFrame {
	public static final long serialVersionUID = 0;

	IconPanel2 panel;

	/**
	 * Creates new form SVGIconDemo
	 * 
	 * @throws IOException
	 */
	public Test() throws IOException {
		panel = new IconPanel2();

		initComponents();

		this.getContentPane().add(panel, BorderLayout.CENTER);

		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	private void initComponents() {

		setLayout(new java.awt.BorderLayout());

	}

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				try {
					new Test().setVisible(true);
				}
				catch (IOException e) {
					e.printStackTrace();
				}
			}
		});
	}

}